### ISSUE TITLE
tourist_arrivals.csv missing

### ISSUE THREAD

**Issue by ChiliDogDaddyO** [alod83/data-science#3]
In https://github.com/alod83/data-science/blob/master/DataVisualization/Altair/AltairAnimation.py, line 9:

df = pd.read_csv('../sources/tourist_arrivals.csv')

I get an error when running.  I tried to find this file the site mentioned in the  article https://towardsdatascience.com/how-to-run-animations-in-altair-and-streamlit-2a0624789ad, but I could not find it.  

I then tried the dataset  https://github.com/alod83/data-science/blob/master/DataVisualization/presenza_negli_alberghi.csv, but it failed on the column named 'Dato'

I then renamed it to 'Date', and it ran without errors, but clicking the Start button produced no output.  

I like the concepts in the Streamlit program, and would like to get it running.  Please advise

**Comment by alod83** [comment]
Hi, 
thanks for your interest to my code and for having found a bug! I have added the CSV source file, thus you can try the original code.
Let me know whether you have solved your problems or not!

Angelica

**Comment by ChiliDogDaddyO** [comment]
Excellent--thank you!
